/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testdocx4j;

import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import until.ConSQL;

/**
 *
 * @author MrOnly
 */
public class DialogThemFile extends javax.swing.JDialog {

    /**
     * Creates new form DialogThemFile
     */
    public static Vector<String> filename = new Vector<>();
    public static String fileVB = "Tên văn bản";
    public static Vector URL = new Vector();
    formMain formChinh = null;

    public DialogThemFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenVB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnChonFile = new javax.swing.JButton();
        btnThemVB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFileChoose = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên văn bản:");

        btnChonFile.setText("Chọn file");
        btnChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonFileActionPerformed(evt);
            }
        });

        btnThemVB.setText("Thêm văn bản");
        btnThemVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVBActionPerformed(evt);
            }
        });

        tblFileChoose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFileChoose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtTenVB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemVB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenVB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemVB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int themvb() {
        try {
            String sql = String.format("INSERT INTO VANBAN(title) values(?)");
            PreparedStatement pstm = ConSQL.con.prepareStatement(sql);
            pstm.setString(1, txtTenVB.getText());
            if (pstm.executeUpdate() > 0) {
                if (themFile() == true) {
                    return 1;
                } else {
                    pstm = ConSQL.con.prepareStatement("delete VanBan where title=?");
                    pstm.setString(1, txtTenVB.getText());
                    pstm.executeQuery();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DialogThemFile.class.getName()).log(Level.SEVERE, null, ex);

        }
        return 0;
    }

    public boolean themFile() {
        int id = getIDbyName(txtTenVB.getText());
        if (id != -1) {
            for (int i = 0; i < URL.size(); i++) {
                try {
                    PreparedStatement pstm = ConSQL.con.prepareStatement("insert into ListFile values (?,?,?,?)");
                    pstm.setInt(1, id);
                    pstm.setString(2, filename.get(i));
                    pstm.setString(3, URL.get(i).toString());
                    pstm.setInt(4, 19);
                    if (pstm.executeUpdate() == 0) {
                        return false;
                    }
                } catch (SQLException ex) {

                    Logger.getLogger(DialogThemFile.class.getName()).log(Level.SEVERE, null, ex);
                    return false;
                }
            }
            return true;
        }
        return false;
    }

    public void updateTable() {
        URL = chonFile.pathFile;
        filename = chonFile.fileName;
        txtTenVB.setText(fileVB);
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        Vector title = new Vector();
        title.add("Tên file");
        title.add("Đường dẫn");
        defaultTableModel.setColumnIdentifiers(title);
        for (int i = 0; i < URL.size(); i++) {
            Vector temp = new Vector();
            temp.add(filename.get(i).toString());
            temp.add(URL.get(i).toString());
            defaultTableModel.addRow(temp);
        }

        tblFileChoose.setModel(defaultTableModel);
    }

    public int getIDbyName(String name) {
        try {
            String sql = "SELECT id from VANBAN where title = N'" + name + "'";
            System.out.println(sql);
            CallableStatement cs = ConSQL.con.prepareCall(sql);
            ResultSet rs = cs.executeQuery();
            while (rs.next()) {
                return Integer.parseInt(rs.getString("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DialogThemFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        return -1;
    }

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        // TODO add your handling code here:
        fileVB = txtTenVB.getText();
        // ChooseFile chooseFile = new ChooseFile();
        chonFile dl = new chonFile(formChinh, true);
        dl.setVisible(true);
        updateTable();

    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnThemVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVBActionPerformed
        if (themvb() > 0) {
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Lỗi! Không thêm được!");
        }
        this.dispose();
    }//GEN-LAST:event_btnThemVBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogThemFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogThemFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogThemFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogThemFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogThemFile dialog = new DialogThemFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFile;
    private javax.swing.JButton btnThemVB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFileChoose;
    private javax.swing.JTextField txtTenVB;
    // End of variables declaration//GEN-END:variables
}
